In [34]:
import pandas as pd
import numpy as np

In [35]:
data = pd.read_csv('Video_Games_Sales_as_at_22_Dec_2016.csv')
data

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006,Sports,Nintendo,41,29,4,8,83,76,51,8,322,Nintendo,E
1,Super Mario Bros.,NES,1985,Platform,Nintendo,29,4,7,1,40,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008,Racing,Nintendo,16,13,4,3,36,82,73,8.3,709,Nintendo,E
3,Wii Sports Resort,Wii,2009,Sports,Nintendo,16,11,3,3,33,80,73,8,192,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11,9,10,1,31,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PS3,2016,Action,Tecmo Koei,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
16715,LMA Manager 2007,X360,2006,Sports,Codemasters,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
16716,Haitaka no Psychedelica,PSV,2016,Adventure,Idea Factory,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
16717,Spirits & Spells,GBA,2003,Platform,Wanadoo,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
16718,Winning Post 8 2016,PSV,2016,Simulation,Tecmo Koei,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16719 entries, 0 to 16718
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16717 non-null  object
 1   Platform         16719 non-null  object
 2   Year_of_Release  16450 non-null  float64
 3   Genre            16717 non-null  object
 4   Publisher        16665 non-null  object
 5   NA_Sales         16719 non-null  float64
 6   EU_Sales         16719 non-null  float64
 7   JP_Sales         16719 non-null  float64
 8   Other_Sales      16719 non-null  float64
 9   Global_Sales     16719 non-null  float64
 10  Critic_Score     8137 non-null   float64
 11  Critic_Count     8137 non-null   float64
 12  User_Score       10015 non-null  object
 13  User_Count       7590 non-null   float64
 14  Developer        10096 non-null  object
 15  Rating           9950 non-null   object
dtypes: float64(9), object(7)
memory usage: 2.0+ MB

In [37]:
platform = pd.DataFrame(data['Platform'].unique())

In [38]:
genre = pd.DataFrame(data['Genre'].unique())
genre.fillna('N/D', inplace=True)
genre = genre.shift()[1:]

In [39]:
publisher = pd.DataFrame(data['Publisher'].unique()).shift()[1:]
publisher.fillna('N/D', inplace=True)
publisher_dict = publisher.to_dict()
publisher_dict = publisher_dict[0]
publisher_dict
new_dict = dict(zip(publisher_dict.values(), publisher_dict.keys()))
# new_dict

In [40]:
na_sales = pd.DataFrame(data['NA_Sales'].unique()).shift()[1:]
eu_sales = pd.DataFrame(data['EU_Sales'].unique()).shift()[1:]
jp_sales = pd.DataFrame(data['JP_Sales'].unique()).shift()[1:]
ot_sales = pd.DataFrame(data['Other_Sales'].unique()).shift()[1:]
global_sales = pd.DataFrame(data['Global_Sales'].unique()).shift()[1:]

In [41]:
critic_score = pd.DataFrame(data['Critic_Score'].unique()).shift()[1:]
user_score = pd.DataFrame(data['User_Score'].unique()).shift()[1:]

In [42]:
platform = pd.DataFrame(data['Platform'].unique()).shift()[1:]
# publisher.fillna('N/D', inplace=True)
platform_dict = platform.to_dict()
platform_dict = platform_dict[0]
platform_dict
new_plat_dict = dict(zip(platform_dict.values(), platform_dict.keys()))
new_plat_dict['N/D'] = 31

platform.loc[len(platform.index)+1] = ['N/D'] 
# new_plat_dict
# platform

In [43]:
genre_dict = genre.to_dict()
genre_dict = genre_dict[0]
genre_dict
new_genre_dict = dict(zip(genre_dict.values(), genre_dict.keys()))
new_genre_dict['N/D'] = 13
new_genre_dict

genre.loc[len(genre.index)+1] = ['N/D'] 
# genre

               0
1         Sports
2       Platform
3         Racing
4   Role-Playing
5         Puzzle
6           Misc
7        Shooter
8     Simulation
9         Action
10      Fighting
11     Adventure
12      Strategy
13           N/D

In [44]:
%pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in /home/evandrocouto/pos/D2APR/d2apr/lib/python3.9/site-packages (8.0.26)
Requirement already satisfied: protobuf>=3.0.0 in /home/evandrocouto/pos/D2APR/d2apr/lib/python3.9/site-packages (from mysql-connector-python) (3.18.0)
Note: you may need to restart the kernel to use updated packages.

In [45]:
import mysql.connector as sql

In [46]:
db_connection = sql.connect(host='localhost', database='games', user='root', password='123456', port=3303)
db_cursor = db_connection.cursor()

In [47]:
for index, row in platform.iterrows():
    query = "INSERT INTO plataforma(nome) VALUES (%s)"
    db_cursor.execute(query, (row[0],))
    db_connection.commit()
#     print("Inserted",db_cursor.rowcount,"row(s) of data.")

In [48]:
for index, row in genre.iterrows():
    query = "INSERT INTO genero(nome) VALUES(%s)"
    db_cursor.execute(query, (row[0],))
    db_connection.commit()
#     print("Inserted",db_cursor.rowcount,"row(s) of data.")

In [49]:
for index, row in publisher.iterrows():
    query = "INSERT INTO publisher(nome) VALUES(%s)"
    db_cursor.execute(query, (row[0],))
#     print("Inserted",db_cursor.rowcount,"row(s) of data.")

In [51]:
cp_data = data[['Name', 'Platform', 'Year_of_Release', 'Genre', 'Publisher']]
cp_data.fillna('N/D', inplace=True)

In [52]:
cp_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16719 entries, 0 to 16718
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16719 non-null  object
 1   Platform         16719 non-null  object
 2   Year_of_Release  16719 non-null  object
 3   Genre            16719 non-null  object
 4   Publisher        16719 non-null  object
dtypes: object(5)
memory usage: 653.2+ KB

In [53]:
cp_cp_data = cp_data.copy()


cp_cp_data['Publisher'] = cp_cp_data['Publisher'].map(new_dict, na_action=None)
cp_cp_data['Genre'] = cp_cp_data['Genre'].map(new_genre_dict, na_action=None)
cp_cp_data['Platform'] = cp_cp_data['Platform'].map(new_plat_dict, na_action=None)
pd.options.display.float_format = '{:.0f}'.format

cp_cp_data['Year_of_Release'] = cp_cp_data['Year_of_Release'].replace('N/D', 0)

cp_cp_data['Genre'].unique()

# genre

               0
1         Sports
2       Platform
3         Racing
4   Role-Playing
5         Puzzle
6           Misc
7        Shooter
8     Simulation
9         Action
10      Fighting
11     Adventure
12      Strategy
13           N/D

In [54]:
for index, row in cp_cp_data.iterrows():
    query = "INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES(%s, %s, %s, %s, %s);"
#     query_string = "INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('{}', {}, {}, {}, {});"
    db_cursor.execute(query, (row[0], row[1], row[2], row[3], row[4],))
    
#     print(query_string.format(row[0], row[1], '{:.0f}'.format(row[2]), row[3], row[4]))
    db_connection.commit()
#     print("Inserted",db_cursor.rowcount,"row(s) of data.")

# cp_cp_data['Genre'].unique()

INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Wii Sports', 1.0, 2006, 1, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Super Mario Bros.', 2.0, 1985, 2, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Mario Kart Wii', 1.0, 2008, 3, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Wii Sports Resort', 1.0, 2009, 1, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Pokemon Red/Pokemon Blue', 3.0, 1996, 4, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Tetris', 3.0, 1989, 5, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('New Super Mario Bros.', 4.0, 2006, 2, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Wii Play', 1.0, 2006, 6, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('New Super Mario Bros. Wii', 1.0, 2009, 2, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Duck Hunt', 2.0, 1984, 7, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Nintendogs', 4.0, 2005, 8, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Mario Kart DS', 4.0, 2005, 3, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Pokemon Gold/Pokemon Silver', 3.0, 1999, 4, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Wii Fit', 1.0, 2007, 1, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Kinect Adventures!', 5.0, 2010, 6, 2.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Wii Fit Plus', 1.0, 2009, 1, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Grand Theft Auto V', 6.0, 2013, 9, 3.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Grand Theft Auto: San Andreas', 7.0, 2004, 9, 3.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Super Mario World', 8.0, 1990, 2, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Brain Age: Train Your Brain in Minutes a Day', 4.0, 2005, 6, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Pokemon Diamond/Pokemon Pearl', 4.0, 2006, 4, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Super Mario Land', 3.0, 1989, 2, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Super Mario Bros. 3', 2.0, 1988, 2, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Grand Theft Auto V', 5.0, 2013, 9, 3.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Grand Theft Auto: Vice City', 7.0, 2002, 9, 3.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Pokemon Ruby/Pokemon Sapphire', 9.0, 2002, 4, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Brain Age 2: More Training in Minutes a Day', 4.0, 2005, 5, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Pokemon Black/Pokemon White', 4.0, 2010, 4, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Gran Turismo 3: A-Spec', 7.0, 2001, 3, 4.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Call of Duty: Modern Warfare 3', 5.0, 2011, 7, 5.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('PokÃ©mon Yellow: Special Pikachu Edition', 3.0, 1998, 4, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Call of Duty: Black Ops 3', 10.0, 2015, 7, 5.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Call of Duty: Black Ops', 5.0, 2010, 7, 5.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Pokemon X/Pokemon Y', 11.0, 2013, 4, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Call of Duty: Black Ops II', 6.0, 2012, 7, 5.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Call of Duty: Black Ops II', 5.0, 2012, 7, 5.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Call of Duty: Modern Warfare 2', 5.0, 2009, 7, 5.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Call of Duty: Modern Warfare 3', 6.0, 2011, 7, 5.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Grand Theft Auto III', 7.0, 2001, 9, 3.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Super Smash Bros. Brawl', 1.0, 2008, 10, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Mario Kart 7', 11.0, 2011, 3, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Call of Duty: Black Ops', 6.0, 2010, 7, 5.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Grand Theft Auto V', 10.0, 2014, 9, 3.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Animal Crossing: Wild World', 4.0, 2005, 8, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Halo 3', 5.0, 2007, 7, 2.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Super Mario 64', 12.0, 1996, 2, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Pokemon HeartGold/Pokemon SoulSilver', 4.0, 2009, 9, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Pokemon Omega Ruby/Pokemon Alpha Sapphire', 11.0, 2014, 4, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Gran Turismo 4', 7.0, 2004, 3, 4.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Super Mario Galaxy', 1.0, 2007, 2, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Super Mario Land 2: 6 Golden Coins', 3.0, 1992, 11, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Grand Theft Auto IV', 5.0, 2008, 9, 3.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Gran Turismo', 13.0, 1997, 3, 4.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Super Mario 3D Land', 11.0, 2011, 2, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Gran Turismo 5', 6.0, 2010, 3, 4.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Call of Duty: Modern Warfare 2', 6.0, 2009, 7, 5.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Super Mario All-Stars', 8.0, 1993, 2, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Grand Theft Auto IV', 6.0, 2008, 9, 3.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Pokemon FireRed/Pokemon LeafGreen', 9.0, 2004, 4, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Super Mario 64', 4.0, 2004, 2, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Call of Duty: Ghosts', 5.0, 2013, 7, 5.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Just Dance 3', 1.0, 2011, 6, 6.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('New Super Mario Bros. 2', 11.0, 2012, 2, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Mario Kart 64', 12.0, 1996, 3, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Halo: Reach', 5.0, 2010, 7, 2.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Final Fantasy VII', 13.0, 1997, 4, 4.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Halo 4', 5.0, 2012, 7, 2.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Gran Turismo 2', 13.0, 1999, 3, 4.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Just Dance 2', 1.0, 2010, 6, 6.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Call of Duty: Ghosts', 6.0, 2013, 7, 5.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Call of Duty 4: Modern Warfare', 5.0, 2007, 7, 5.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Donkey Kong Country', 8.0, 1994, 2, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Minecraft', 5.0, 2013, 6, 2.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Animal Crossing: New Leaf', 11.0, 2012, 8, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Mario Party DS', 4.0, 2007, 6, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('The Elder Scrolls V: Skyrim', 5.0, 2011, 4, 7.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Super Mario Kart', 8.0, 1992, 3, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('FIFA 16', 10.0, 2015, 1, 8.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Halo 2', 14.0, 2004, 7, 2.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Wii Party', 1.0, 2010, 6, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Mario Party 8', 1.0, 2007, 6, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('FIFA Soccer 13', 6.0, 2012, 9, 8.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('GoldenEye 007', 12.0, 1997, 7, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Pokemon Black 2/Pokemon White 2', 4.0, 2012, 4, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Final Fantasy X', 7.0, 2001, 4, 4.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('The Sims 3', 15.0, 2009, 8, 8.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Mario & Sonic at the Olympic Games', 1.0, 2007, 1, 9.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Star Wars Battlefront (2015)', 10.0, 2015, 7, 8.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Final Fantasy VIII', 13.0, 1999, 4, 10.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Pac-Man', 16.0, 1982, 5, 11.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('PokÃ©mon Platinum Version', 4.0, 2008, 4, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Grand Theft Auto: Liberty City Stories', 17.0, 2005, 9, 3.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Call of Duty: Advanced Warfare', 10.0, 2014, 7, 5.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('The Legend of Zelda: Ocarina of Time', 12.0, 1998, 9, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('FIFA 17', 10.0, 2016, 1, 8.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Crash Bandicoot 2: Cortex Strikes Back', 13.0, 1997, 2, 4.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Super Smash Bros. for Wii U and 3DS', 11.0, 2014, 10, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Super Mario Galaxy 2', 1.0, 2010, 2, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Super Mario Bros. 2', 2.0, 1988, 2, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Call of Duty: Black Ops 3', 18.0, 2015, 7, 5.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Call of Duty: World at War', 5.0, 2008, 7, 5.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Battlefield 3', 5.0, 2011, 7, 8.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Need for Speed Underground', 7.0, 2003, 3, 8.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Just Dance', 1.0, 2009, 6, 6.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Battlefield 3', 6.0, 2011, 7, 8.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Fallout 4', 10.0, 2015, 4, 7.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Tekken 3', 13.0, 1998, 10, 4.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('The Legend of Zelda: Twilight Princess', 1.0, 2006, 9, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Pokemon Sun/Moon', 11.0, 2016, 4, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Crash Bandicoot 3: Warped', 13.0, 1998, 2, 4.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Mario Kart 8', 19.0, 2014, 3, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Super Smash Bros. Melee', 20.0, 2001, 10, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Mario Kart: Double Dash!!', 20.0, 2003, 3, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Need for Speed Underground 2', 7.0, 2004, 3, 8.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Medal of Honor: Frontline', 7.0, 2002, 7, 8.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Crash Bandicoot', 13.0, 1996, 2, 4.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Just Dance 4', 1.0, 2012, 6, 6.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Gears of War 2', 5.0, 2008, 7, 2.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Uncharted 3: Drake's Deception', 6.0, 2011, 9, 4.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Zumba Fitness', 1.0, 2010, 1, 12.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Call of Duty 4: Modern Warfare', 6.0, 2007, 7, 5.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Uncharted 2: Among Thieves', 6.0, 2009, 9, 4.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('FIFA 12', 6.0, 2011, 1, 8.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Big Brain Academy', 4.0, 2005, 6, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('The Legend of Zelda', 2.0, 1986, 9, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Red Dead Redemption', 6.0, 2010, 9, 3.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('FIFA 14', 6.0, 2013, 1, 8.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Assassin's Creed III', 6.0, 2012, 9, 6.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Donkey Kong Country Returns', 1.0, 2010, 2, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Halo: Combat Evolved', 14.0, 2001, 7, 2.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('The Elder Scrolls V: Skyrim', 6.0, 2011, 4, 7.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('PokÃ©mon Emerald Version', 9.0, 2004, 4, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Kingdom Hearts', 7.0, 2002, 4, 4.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('PokÃ©mon Crystal Version', 3.0, 2000, 4, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Halo 3: ODST', 5.0, 2009, 7, 2.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Red Dead Redemption', 5.0, 2010, 9, 3.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Super Mario Sunshine', 20.0, 2002, 2, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Street Fighter II: The World Warrior', 8.0, 1992, 10, 13.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('World of Warcraft', 15.0, 2004, 4, 5.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Driver', 13.0, 1999, 9, 14.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Gears of War 3', 5.0, 2011, 7, 2.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Kinect Sports', 5.0, 2010, 1, 2.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Gears of War', 5.0, 2006, 7, 2.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('FIFA 15', 10.0, 2014, 1, 8.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Metal Gear Solid 2: Sons of Liberty', 7.0, 2001, 9, 15.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Sonic the Hedgehog 2', 21.0, 1992, 2, 9.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Metal Gear Solid', 13.0, 1998, 9, 15.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Metal Gear Solid 4: Guns of the Patriots', 6.0, 2008, 9, 15.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Final Fantasy XII', 7.0, 2006, 4, 16.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('The Last of Us', 6.0, 2013, 9, 17.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('LittleBigPlanet', 6.0, 2008, 2, 4.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Resident Evil 2', 13.0, 1998, 9, 18.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Dragon Quest IX: Sentinels of the Starry Skies', 4.0, 2009, 4, 1.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Tekken 2', 13.0, 1996, 10, 4.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('Destiny', 10.0, 2014, 7, 5.0);
INSERT INTO games.game(nome, plataforma, ano_lancamento, genero, publisher) VALUES('LEGO Star Wars: The Complete Saga', 1.0, 2007, 9, 19.0);

ProgrammingError: 1054 (42S22): Unknown column 'nan' in 'field list'